//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donkey_Kong_IHM.Res {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Donkey_Kong_IHM.Res.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Touches.
        /// </summary>
        public static string Button_Keys {
            get {
                return ResourceManager.GetString("Button_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle partie.
        /// </summary>
        public static string Button_NewGame {
            get {
                return ResourceManager.GetString("Button_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string Button_Quit {
            get {
                return ResourceManager.GetString("Button_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string Button_Quitter {
            get {
                return ResourceManager.GetString("Button_Quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètre.
        /// </summary>
        public static string Button_Settings {
            get {
                return ResourceManager.GetString("Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fenêtre du jeu.
        /// </summary>
        public static string FenetreJeu_Title {
            get {
                return ResourceManager.GetString("FenetreJeu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aller à droite.
        /// </summary>
        public static string Label_AllerDroite {
            get {
                return ResourceManager.GetString("Label_AllerDroite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aller à gauche.
        /// </summary>
        public static string Label_AllerGauche {
            get {
                return ResourceManager.GetString("Label_AllerGauche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à © 1983-2010 Nintendo.
        /// </summary>
        public static string Label_Copyright {
            get {
                return ResourceManager.GetString("Label_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descendre l&apos;échelle.
        /// </summary>
        public static string Label_DescendreEchelle {
            get {
                return ResourceManager.GetString("Label_DescendreEchelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonctionnalité :.
        /// </summary>
        public static string Label_Fonctionnalite {
            get {
                return ResourceManager.GetString("Label_Fonctionnalite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grimper à l&apos;échelle.
        /// </summary>
        public static string Label_GrimperEchelle {
            get {
                return ResourceManager.GetString("Label_GrimperEchelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue :.
        /// </summary>
        public static string Label_Langue {
            get {
                return ResourceManager.GetString("Label_Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Made in Japan.
        /// </summary>
        public static string Label_MadeInJapan {
            get {
                return ResourceManager.GetString("Label_MadeInJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauter.
        /// </summary>
        public static string Label_Sauter {
            get {
                return ResourceManager.GetString("Label_Sauter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Touche associée :.
        /// </summary>
        public static string Label_ToucheAssociee {
            get {
                return ResourceManager.GetString("Label_ToucheAssociee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume :.
        /// </summary>
        public static string Label_Volume {
            get {
                return ResourceManager.GetString("Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Donkey Kong - Accueil.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string Parametre_Title {
            get {
                return ResourceManager.GetString("Parametre_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à anglais.
        /// </summary>
        public static string Radio_English {
            get {
                return ResourceManager.GetString("Radio_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à français.
        /// </summary>
        public static string Radio_French {
            get {
                return ResourceManager.GetString("Radio_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration des touches.
        /// </summary>
        public static string Touches_Title {
            get {
                return ResourceManager.GetString("Touches_Title", resourceCulture);
            }
        }
    }
}
